### ISSUE TITLE
[New feature]Add the error message for team storage

### ISSUE THREAD

**Issue by Morningssir** [Morningssir/Openpai-bug-fix#10]
## Description
1. If the job protocol not config team storage, fetch storage details and config default items in UI view
2. If the job protocol has already existed  the storages, synchronize the storage details(mountPath) and selected config names 

## Work Plan
- [x] Fetch team storage config and show the default selection on the page
- [x] Change the job protocol's storages when users select the team storage
- [x] Show the team storage detail when clicking the detail button
- [x] Change the UI view when modifying the yaml page
- [ ] Show the error message if not find selected team storage configs
- [ ] Solve the rebuild when toggle the yaml page
